# Basic Usage

In this notebook we go through some example usage of the base classes offered by TN4QA. These are:

* Tensor
* TensorNetwork
* MatrixProductState
* MatrixProductOperator



In [61]:
from tn4qa.tensor import Tensor
from tn4qa.tn import TensorNetwork
from tn4qa.mps import MatrixProductState 
from tn4qa.mpo import MatrixProductOperator

import numpy as np
from qiskit import QuantumCircuit
from copy import deepcopy

## Tensor

In [63]:
data = np.array(range(12)).reshape(2,3,2)
t = Tensor(data, ["a", "b", "c"], ["MyFirstTensor"])
print(t.data.todense())
print(t.dimensions)
print(t.indices)
print(t.labels)
print(t)
print(t.get_dimension_of_index("b"))

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
(2, 3, 2)
['a', 'b', 'c']
['MyFirstTensor']
Tensor with shape (2, 3, 2) and indices ['a', 'b', 'c']
3


In [10]:
t2 = Tensor.rank_3_copy(indices=["a","d","e"])
print(t2.data.todense())
print(t2.dimensions)
print(t2.indices)
print(t2.labels)

[[[1.+0.j         0.+0.j        ]
  [0.+0.j         1.+0.j        ]]

 [[0.+0.j         0.+0.j        ]
  [0.+0.j         0.+1.41421356j]]]
(2, 2, 2)
['a', 'd', 'e']
['T1', 'copy3']


## TensorNetwork

In [66]:
tn = TensorNetwork([t,t2])
print(tn)
print(tn.get_internal_indices())
print(tn.get_external_indices())

contracted_t = tn.contract_entire_network()
print(contracted_t)

Tensor Network containing: 
Tensor with shape (2, 3, 2) and indices ['a', 'b', 'c'] 
Tensor with shape (2, 2, 2) and indices ['a', 'd', 'e'] 

['a']
['b', 'c', 'd', 'e']
Tensor with shape (3, 2, 2, 2) and indices ['b', 'c', 'd', 'e']


## MatrixProductState

Matrix Product States represent quantum states.

In [69]:
# mps = MatrixProductState()

# qc = QuantumCircuit(4)
# qc.h(0)
# qc.cx(0,1)
# qc.cx(1,2)
# qc.cx(2,3)
# mps = MatrixProductState.from_qiskit_circuit(qc, 16)
# mps.draw()
# print(mps.to_dense_array())

# mps = MatrixProductState.random_mps(8, 12, 4)
# print(mps.bond_dimension)
# print(mps.num_sites)
# print(mps.physical_dimension)
# print(mps)

mps = MatrixProductState.random_quantum_state_mps(6, 4)
print(mps.physical_dimension)
print(mps)

2
Tensor Network containing: 
Tensor with shape (4, 2) and indices ['B1', 'P1'] 
Tensor with shape (4, 4, 2) and indices ['B1', 'B2', 'P2'] 
Tensor with shape (4, 4, 2) and indices ['B2', 'B3', 'P3'] 
Tensor with shape (4, 4, 2) and indices ['B3', 'B4', 'P4'] 
Tensor with shape (4, 4, 2) and indices ['B4', 'B5', 'P5'] 
Tensor with shape (4, 2) and indices ['B5', 'P6'] 



In [37]:
mps = MatrixProductState.random_quantum_state_mps(8, 16)
mps_16 = deepcopy(mps)
print(mps.compute_inner_product(mps))
mps.compress(8)
print(mps.compute_inner_product(mps_16))
mps.compress(4)
print(mps.compute_inner_product(mps_16))
mps.compress(2)
print(mps.compute_inner_product(mps_16))
mps.compress(1)
print(mps.compute_inner_product(mps_16))

(1+0j)
(0.9999999997456148+0j)
(0.9999962115609836+0j)
(0.9993715451215373+0j)
(0.9204417077418471+0j)


In [72]:
mps_zero = MatrixProductState.all_zero_mps(4)

qc_one = QuantumCircuit(4)
qc_one.x([0,1,2,3])
mps_one = MatrixProductState.from_qiskit_circuit(qc_one, 16)

# print(mps_zero.to_dense_array())
# print(mps_one.to_dense_array())

# mps_zero.multiply_by_constant(np.sqrt(1/2))
# mps_one.multiply_by_constant(np.sqrt(1/2))
mps_ghz = mps_zero + mps_one
print(mps_ghz.to_dense_array())
mps_ghz.normalise()
print(mps_ghz.to_dense_array())

[1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 1.+0.j]
[0.70710678+0.j 0.        +0.j 0.        +0.j 0.        +0.j
 0.        +0.j 0.        +0.j 0.        +0.j 0.        +0.j
 0.        +0.j 0.        +0.j 0.        +0.j 0.        +0.j
 0.        +0.j 0.        +0.j 0.        +0.j 0.70710678+0.j]


## MatrixProductOperator

Matrix Product Operators represent operators. 

In [76]:
# mpo = MatrixProductOperator()

# mpo = MatrixProductOperator.identity_mpo(4)
# print(mpo.to_dense_array())
# print(mpo)
# mpo.draw()

# qc = QuantumCircuit(2)
# qc.x(0)
# qc.x(1)
# mpo = MatrixProductOperator.from_qiskit_circuit(qc, 16)
# print(mpo.to_dense_array())

# mpo = MatrixProductOperator.from_pauli_string("XX")
# print(mpo.to_dense_array())

ham_dict = {"XX" : 0.1, "II" : -0.1}
mpo = MatrixProductOperator.from_hamiltonian(ham_dict, 16)
print(mpo.to_dense_array())

[[-0.1  0.   0.   0.1]
 [ 0.  -0.1  0.1  0. ]
 [ 0.   0.1 -0.1  0. ]
 [ 0.1  0.   0.  -0.1]]


In [77]:
mpo1 = MatrixProductOperator.from_pauli_string("XX")
# mpo1.multiply_by_constant(0.1)

# mpo2 = MatrixProductOperator.from_pauli_string("II")
# mpo2.multiply_by_constant(-0.1)

# mpo = mpo1 + mpo2
# print(mpo.to_dense_array())

mpo3 = MatrixProductOperator.from_pauli_string("XX")
mpo = mpo1 * mpo3
print(mpo.to_dense_array())

[[1.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 1.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 1.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 1.+0.j]]


In [79]:
mpo = MatrixProductOperator.from_pauli_string("XX")
mps = MatrixProductState.equal_superposition_mps(2)
print(mps.compute_expectation_value(mpo))

(1.0000000000000002+0j)
